# Generated by Django 4.2.1 on 2023-06-11 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_comuna_estado_genero_metadata_ordendecompra_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repuesto',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='repuesto',
            name='descuento',
        ),
        migrations.RemoveField(
            model_name='repuesto',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='repuesto',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='repuesto',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='repuesto',
            name='precio_antes',
        ),
        migrations.RemoveField(
            model_name='repuesto',
            name='precio_total',
        ),
        migrations.RemoveField(
            model_name='repuesto',
            name='sku',
        ),
        migrations.RemoveField(
            model_name='repuesto',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='repuesto',
            name='titulo',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='descuento',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='precio_antes',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='precio_total',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='sku',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='titulo',
        ),
        migrations.AddField(
            model_name='producto',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='producto',
            name='titulo',
            field=models.CharField(default='', max_length=100),
        ),
    ]
