# Generated by Django 4.2.1 on 2023-07-02 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_vehiculo_marca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aprobacion',
            name='vendedor',
            field=models.ForeignKey(limit_choices_to={'perfiles__tipo_usuario__in': ['VENDEDOR', 'ADMINISTRADOR']}, on_delete=django.db.models.deletion.CASCADE, to='home.usersmetadata'),
        ),
    ]
