# Generated by Django 4.2.1 on 2023-06-12 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_producto_adiccional_alter_producto_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='adiccional',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(default=''),
        ),
    ]
