# Generated by Django 4.2.1 on 2023-07-03 00:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0006_rename_fecha_aprobacion_aprobacion_fecha_revision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersmetadata',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usersmetadata', to=settings.AUTH_USER_MODEL),
        ),
    ]
