# Generated by Django 4.2.1 on 2023-07-03 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_usersmetadata_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='estado',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.estado'),
        ),
        migrations.AddField(
            model_name='documento',
            name='ordenDeCompra',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.ordendecompra'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='users_metadata',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='documentos', to='home.usersmetadata'),
        ),
    ]
