# Generated by Django 4.2.1 on 2023-07-03 12:37

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_documento_estado_documento_ordendecompra_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepuestoCategoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='nombre')),
            ],
            options={
                'verbose_name': 'repuesto Categoría',
                'verbose_name_plural': 'repuesto Categorías',
                'db_table': 'repuesto_categoria',
            },
        ),
        migrations.AddField(
            model_name='repuesto',
            name='tipo_repuesto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.repuestocategoria'),
        ),
    ]
