# Generated by Django 4.2.1 on 2023-06-14 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_ubicacion_alter_vehiculo_volante_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculo',
            name='ubicacion',
        ),
        migrations.AddField(
            model_name='producto',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.sucursal'),
        ),
        migrations.DeleteModel(
            name='Ubicacion',
        ),
    ]
