# Generated by Django 4.2.1 on 2023-06-14 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_vehiculo_ubicacion_producto_sucursal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfiles',
            name='tipo_usuario',
        ),
    ]
