# Generated by Django 4.2.1 on 2023-06-14 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_remove_perfiles_tipo_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repuesto',
            name='proveedor',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='proveedor',
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='transmision',
            field=models.CharField(choices=[('MECANICA', 'Mecánica'), ('AUTOMATICA', 'Automática')], max_length=20),
        ),
    ]
