# Generated by Django 4.2.2 on 2023-06-14 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_remove_repuesto_proveedor_remove_vehiculo_proveedor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='modelo',
            field=models.CharField(max_length=50),
        ),
    ]
